### ISSUE TITLE
Failed Installation in Blender 2.93.4

### ISSUE THREAD

**Issue by schematique** [norrid/DAEClean#1]
After attempting to install on Blender 2.93.4, the add-on doesn't show up in the Preferences Add-ons list, and of course does not show up in the tools panel in the viewport. Does the add-on support this version of Blender, or am I totally barking up the wrong tree?

After pointing blender to the downloaded zip file, I do see an info log entry that states:

`Modules Installed () from '[File Path]' into 'C:\\Users\\USERNAME\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons'`

That's all I'm seeing in the way of success/failure feedback, however.

Very excited about the capabilities of the add-on! Excited enough to make this my first ever post on github, so I apologize if I'm not approaching this in the right way or the right place. Please let me know if any additional information is required. I appreciate your work on this and your other add-ons.

**Comment by norrid** [comment]
Hi, I've been using it on every version since 2.80 and it worked fine on 2.93.4 for me. If you go to the file path that you mention (..AppData\\Roaming\\Blender\...), take a look in the addons directory and if you see DAEClean, delete that directory and try installing the .zip again.

Thanks for the message and please let me know if this works. If you're still having issues, let me know and I'll work out a sollution.
